server:
  port: 9527

spring:
  application:
    name: cloud-gateway

  cloud:
    discovery:
      locator:
        enable: true  # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
    gateway:    # SpringCloud GateWay  (网关)
      routes:   # 路由
        - id: payment_routh1                    # 路由的ID，没有固定要求但要唯一，建议配个服务名
          uri: lb://cloud-payment-service       # 匹配后提供服务的路由地址
          predicates:   # 断言
            - Path=/service/payment/**          # 路径相匹配的进行路由

#        - id: payment_routh2                   # 可添加多个路由
#            uri: lb://cloud-payment-service
#            predicates:
#              - Path=/service/payment/save

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka